### ISSUE TITLE
fix compatibility with numpy 1.9

### ISSUE THREAD

**Issue by juliameier** [SGWissInfo/pyphant1#103]
All modules that use the numpy.oldnumeric module have to be updated to proper numpy since oldnumeric was removed with numpy version 1.9

**Comment by GitEdit** [comment]
Two modules use oldnumeric:
.../pyphant1/src/pyphant/pyphant/quantities/__init__.py
and
.../pyphant1/src/pyphant/pyphant/quantities/PhysicalQuantities.py
